spring.datasource.url=jdbc:postgresql://ep-little-thunder-azqmb031.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1tQqN2VkGMsH

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}

# =====================================================
# OPENAI
# =====================================================

openai.api-key=${OPENAI_API_KEY:}

# =====================================================
# AUDIO
# =====================================================

audio.storage.path=${AUDIO_STORAGE_PATH:${user.dir}/audio-data/tu-vung}

audio.python.command=${AUDIO_PYTHON_COMMAND:python3}

# =====================================================
# GEMINI AI (Hỗ trợ 1 hoặc nhiều API Key cách nhau bởi dấu phẩy qua biến môi trường GEMINI_API_KEY)
# =====================================================
gemini.api-keys=${GEMINI_API_KEY:}

